{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "openvpn.fullname" . }}
  labels:
    app: {{ template "openvpn.name" . }}
    chart: {{ template "openvpn.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.enabled .Values.persistence.qcloudCbsId }}
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-{{ template "openvpn.fullname" . }}
    labels:
      app: {{ template "openvpn.name" . }}
      chart: {{ template "openvpn.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    accessModes:
    - {{ .Values.persistence.accessMode | quote }}
    capacity:
      storage: {{ .Values.persistence.size | quote }}
    persistentVolumeReclaimPolicy: Retain
    qcloudCbs:
      cbsDiskId: {{ .Values.persistence.qcloudCbsId | quote }}
      fsType: ext4
      storageClassName: cbs
      volumeMode: Filesystem
{{- else }}
  {{- if and .Values.persistence.enabled (.Values.persistence.templatePV) }}
    {{ toYaml .Values.persistence.templatePV | indent 2 }}
  {{- end }}
{{- end }}